% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Jan-2024 18:03:29
%  MATLAB version: 23.2.0.2459199 (R2023b) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('Kacperr_Dusza.mat');

X = [5 3 2 1];


Z = ...
  [5 2 1 0;
   1 2 5 0;
   0 0 0 0;
   0 0 0 150];

a = 2;

a_1 = 4;

ans = [5 2 1];

x = [3 2 5 1 7 8];

y = [12; 23; 1256; 623; 2];

z = saveVarsMat.z; % <1x0 double> empty object

clear saveVarsMat;

%% Generacja liczb pseudolosowych - pierwszy program w Matlabie
% Generacja liczb pseudolosowych o rozkładzie normalnym i rysowanie
% histogramu

%Autor: Kacper Dusza Data: 05.01.2024
%Data: 05.01.2024

clear all;close all; clc
%% Generacja liczb pseudolosowych

N=100;
A=randn(N,2);

%% Histogram
%Wyświetlanie histogramu
histogram(A,25)         %R = 25 - liczba przedziałów histogramu

title('Histogram liczb pseudolosowych');
xlabel('Wartosc zmiennej losowej[-]');
ylabel('Liczebność[-]');
grid on;

x2 = randn(N,3);

x3=A.^2;

figure; histogram(x3,15)         %R = 15 - liczba przedziałów histogramu

title('Histogram liczb pseudolosowych');
xlabel('Wartosc zmiennej losowej[-]');
ylabel('Liczebność[-]');
grid on;


